# --- ОСНОВНЫЕ НАСТРОЙКИ ---
redir-port: 7892
tproxy-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: false
unified-delay: true
tcp-concurrent: true

# --- НАСТРОЙКИ UI/ПРОФИЛЯ ---
external-controller: '0.0.0.0:9090'
secret: 'admin'
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
profile:
  store-selected: true
  store-fake-ip: true

# --- SNIFFER ---
sniffer:
  enable: true
  override-destination: false
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880
    TLS:
      ports:
        - 443
        - 8443
    QUIC:
  skip-dst-address:
    - 224.0.0.0/3
    - 10.0.0.0/8
    - 127.0.0.0/8
    - 100.64.0.0/10
    - 172.16.0.0/12
    - 198.18.0.0/15
    - 169.254.0.0/16
    - 192.168.0.0/16
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 198.51.100.0/24
    - 203.0.113.0/24
    - fc00::/7
    - ff00::/8
    - fe80::/10
    - ::/127

# --------------------------------------------------------------------
# --- Секция 1: ПРОВАЙДЕРЫ ПРОКСИ ---
# --------------------------------------------------------------------
proxies:
  - name: WDTT
    type: direct
    interface-name: nwg0

# --------------------------------------------------------------------
# --- Секция 2: ГРУППЫ ПРОКСИ ---
# --------------------------------------------------------------------
proxy-groups:
  - name: VPN
    type: fallback
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    proxies:
      - WDTT
    url: http://www.gstatic.com/generate_204
    interval: 120
    tolerance: 50

  - name: AI
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png
    type: select
    hidden: true
    proxies:
      - VPN
    
  - name: 📺 Youtube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies:
      - 🔓 Без VPN
      - VPN

  - name: 💬 Discord
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    type: select
    proxies:
      - 🔓 Без VPN
      - VPN
      

  - name: 🎮 Игры
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies:
      - 🔓 Без VPN
      - VPN

  - name: 🔓 Без VPN
    type: select
    hidden: true
    proxies:
      - DIRECT

  - name: ⛔ Блок
    type: select
    hidden: true
    proxies:
      - REJECT

# --------------------------------------------------------------------
# --- Секция 3: ПРОВАЙДЕРЫ ПРАВИЛ ---
# --------------------------------------------------------------------
rule-providers:
  private-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/private.mrs
    path: ./ruleset/geosite-private.mrs
    proxy: VPN
    interval: 2592000
  category-ru:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/category-ru.mrs
    path: ./ruleset/category-ru.mrs
    proxy: VPN
    interval: 86400
  whitelist:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/whitelist.mrs
    path: ./ruleset/whitelist.mrs
    proxy: VPN
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/microsoft.mrs
    path: ./ruleset/microsoft.mrs
    proxy: VPN
    interval: 86400
  apple:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/apple.mrs
    path: ./ruleset/apple.mrs
    proxy: VPN
    interval: 86400
  google-play:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/google-play.mrs
    path: ./ruleset/google-play.mrs
    proxy: VPN
    interval: 86400
  epicgames:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/epicgames.mrs
    path: ./ruleset/epicgames.mrs
    proxy: VPN
    interval: 86400
  origin:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/origin.mrs
    path: ./ruleset/origin.mrs
    proxy: VPN
    interval: 86400
  riot:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/riot.mrs
    path: ./ruleset/riot.mrs
    proxy: VPN
    interval: 86400
  escapefromtarkov:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/escapefromtarkov.mrs
    path: ./ruleset/escapefromtarkov.mrs
    proxy: VPN
    interval: 86400
  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/steam.mrs
    path: ./ruleset/steam.mrs
    proxy: VPN
    interval: 86400
  twitch:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch.mrs
    path: ./ruleset/twitch.mrs
    proxy: VPN
    interval: 86400
  pinterest:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/pinterest.mrs
    path: ./ruleset/pinterest.mrs
    proxy: VPN
    interval: 86400
  faceit:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/faceit.mrs
    path: ./ruleset/faceit.mrs
    proxy: VPN
    interval: 86400
  private-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geoip/release/mihomo/private.mrs
    path: ./ruleset/geoip-private.mrs
    proxy: VPN
    interval: 2592000
  direct-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geoip/release/mihomo/direct.mrs
    path: ./ruleset/direct-ips.mrs
    proxy: VPN
    interval: 86400
  github:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/github.mrs
    path: ./ruleset/github.mrs
    proxy: VPN
    interval: 86400
  twitch-ads:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch-ads.mrs
    path: ./ruleset/twitch-ads.mrs
    proxy: VPN
    interval: 86400
  youtube:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/youtube.mrs
    path: ./ruleset/youtube.mrs
    proxy: VPN
    interval: 86400
  telegram-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/telegram.mrs
    path: ./ruleset/telegram.mrs
    proxy: VPN
    interval: 86400
  telegram-ips:
    type: http
    behavior: ipcidr
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/telegram.yaml
    path: ./ruleset/telegram.yaml
    proxy: VPN
    interval: 86400
  win-spy:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/win-spy.mrs
    path: ./ruleset/win-spy.mrs
    proxy: VPN
    interval: 86400
  torrent-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/torrent.mrs
    path: ./ruleset/torrent-domains.mrs
    proxy: VPN
    interval: 86400
  category-ads:
    type: http
    behavior: domain
    format: mrs
    url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/category-ads.mrs
    path: ./ruleset/category-ads.mrs
    proxy: VPN
    interval: 86400
  ai:
    type: http
    behavior: domain
    format: mrs
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs"
    path: ./ruleset/ai.mrs
    proxy: VPN
    interval: 86400

# --------------------------------------------------------------------
# --- Секция 4: ПРАВИЛА ---
# --------------------------------------------------------------------
rules:
  - RULE-SET,private-ips,DIRECT
  - RULE-SET,private-domains,DIRECT
  - RULE-SET,category-ads,REJECT
  - RULE-SET,win-spy,REJECT
  - RULE-SET,torrent-domains,DIRECT
  - DOMAIN-SUFFIX,yandex.ru,DIRECT
  - DOMAIN-SUFFIX,ya.ru,DIRECT
  - DOMAIN-KEYWORD,yandex,DIRECT
  - RULE-SET,ai,AI
  - RULE-SET,google-play,VPN
  - RULE-SET,twitch-ads,VPN
  - RULE-SET,youtube,📺 Youtube
  - RULE-SET,telegram-domains,VPN
  - RULE-SET,telegram-ips,VPN
  - RULE-SET,github,VPN
  - RULE-SET,epicgames,🎮 Игры
  - RULE-SET,origin,🎮 Игры
  - RULE-SET,riot,🎮 Игры
  - RULE-SET,escapefromtarkov,🎮 Игры
  - RULE-SET,steam,🎮 Игры
  - RULE-SET,faceit,🎮 Игры
  - RULE-SET,twitch,VPN
  - RULE-SET,microsoft,VPN
  - RULE-SET,apple,DIRECT
  - RULE-SET,pinterest,DIRECT
  - RULE-SET,category-ru,DIRECT
  - RULE-SET,whitelist,DIRECT
  - RULE-SET,direct-ips,DIRECT
  - MATCH,VPN
