package com.wdtt.plus.ui

/**
 * Android-приложения сервисов, которые остаются доступными при ограничениях
 * мобильного интернета, а также приложения, часто ограничивающие работу через VPN.
 *
 * Список пакетов и названий актуализирован по перечням Минцифры и карточкам
 * приложений в российских магазинах. Поиск выполняется только среди уже
 * установленных приложений, поэтому отсутствующие пакеты ни на что не влияют.
 */
internal val QuickExclusionExactPackages = setOf(
    // Государственные и социальные сервисы
    "ru.rostel",
    "ru.gosuslugi.goskey",
    "com.octopod.russianpost.client.android",
    "ru.crptech.mark",

    // Банки и платежи
    "ru.sberbankmobile",
    "ru.tinkoff.mb",
    "ru.vtb24.mobilebanking.android",
    "ru.alfabank.mobile.android",
    "logo.com.mbanking",
    "ru.mts.bank",
    "ru.lewis.dbo",
    "ru.gazprombank.android.mobilebank.app",
    "ru.nspk.mirpay",
    "ru.nspk.sbpay",

    // Соцсети, связь и магазины приложений
    "com.vkontakte.android",
    "com.vk.im",
    "com.vk.vkvideo",
    "ru.vk.music",
    "ru.ok.android",
    "ru.oneme.app",
    "ru.mail.mailapp",
    "ru.mail.cloud",
    "ru.vk.store",

    // Маркетплейсы, объявления и работа
    "ru.ozon.app.android",
    "com.wildberries.ru",
    "ru.beru.android",
    "ru.megamarket",
    "ru.sbermarket",
    "ru.instamart",
    "ru.samokat.android",
    "com.avito.android",
    "ru.domclick.mortgage",
    "ru.hh.android",

    // Яндекс
    "ru.yandex.searchplugin",
    "ru.yandex.yandexmaps",
    "ru.yandex.music",
    "ru.kinopoisk",
    "com.yandex.browser",
    "ru.yandex.taxi",

    // Операторы связи
    "ru.mts",
    "ru.beeline.services",
    "ru.tele2.mytele2",
    "ru.megafon.mlk",

    // Магазины, доставка и рестораны
    "ru.vkusvill",
    "com.icemobile.lenta.prod",
    "ru.reksoft.okey",
    "ru.myauchan.droid",
    "www.metro.com",
    "ru.tander.magnit",
    "ru.pyaterochka.app.browser",
    "ru.perekrestok.app",
    "club.chizhik",
    "com.logistic.sdek",
    "ru.dodopizza.app",
    "ru.burgerking",
    "com.apegroup.mcdonaldsrussia",

    // Транспорт, навигация и путешествия
    "ru.dublgis.dgismobile",
    "ru.rzd.pass",
    "ru.tutu.tutu_emp",
    "com.carshering",
    "youdrive.today",
    "com.belkacar",
    "ru.aeroflot",
    "com.taxsee.taxsee",
    "ru.maximoff.max",

    // Видео, музыка, новости и погода
    "ru.rutube.app",
    "ru.ivi.client",
    "ru.more.play",
    "ru.zen.android",
    "gpm.tnt_premier",
    "ru.mts.mtstv",
    "ru.radioplayer",
    "com.gismeteo.client",
)

internal val QuickExclusionKeywords = listOf(
    "sber", "сбер",
    "tinkoff", "t-bank", "tbank", "тинькофф", "т-банк", "тбанк",
    "vtb", "втб",
    "alfa", "alpha", "альфа",
    "psbank", "промсвязьбанк", "псб",
    "gazprombank", "газпромбанк",
    "mir pay", "mirpay", "мир пэй",
    "sbpay", "сбпэй",
    "ozon", "озон",
    "wildberries", "вайлдберриз",
    "yandex", "яндекс",
    "vkontakte", "вконтакте",
    "rutube", "рутуб",
    "gosuslugi", "госуслуг", "госключ",
    "честный знак",
    "dublgis", "2gis", "dgis", "дубльгис",
    "avito", "авито",
    "domclick", "домклик",
    "headhunter", "hh.ru",
    "mts", "мтс",
    "beeline", "билайн",
    "megafon", "мегафон",
    "tele2", "теле2",
    "mail.ru", "mailapp",
    "ok.ru", "odnoklassniki", "одноклассники",
    "kinopoisk", "кинопоиск",
    "samokat", "самокат",
    "megamarket", "мегамаркет", "sbermarket",
    "kuper", "купер", "instamart",
    "rostel", "ростел",
    "почта россии", "russianpost",
    "max: общение", "макс: общение", "oneme",
    "vkusvill", "вкусвилл",
    "lenta.prod", "лента – доставка", "лента - доставка",
    "okeydostavka", "гипермаркеты и доставка",
    "myauchan", "мой ашан",
    "metro: продукты", "метро: продукты",
    "tander.magnit", "магнит: акции",
    "pyaterochka", "пятёрочка:", "пятерочка:",
    "perekrestok", "перекрёсток доставка", "перекресток доставка",
    "club.chizhik", "чижик - доставка", "чижик — доставка",
    "cdek", "сдэк",
    "dostavista", "достависта",
    "dodopizza", "додо пицца",
    "burgerking", "бургер кинг",
    "mcdonaldsrussia", "вкусно — и точка", "вкусно - и точка",
    "детский мир", "detmir",
    "петрович", "petrovich",
    "spar —", "spar -", "мой spar",
    "дикси", "dixy",
    "vprok", "впрок",
    "5post", "fivepost",
    "много лосося",
    "rzd.pass", "ржд пассажирам",
    "tutu", "туту:",
    "carshering", "делимобиль",
    "citydrive", "ситидрайв", "youdrive",
    "belkacar", "белкаcar",
    "aeroflot", "аэрофлот",
    "pobeda", "победа",
    "s7 airlines",
    "деловые линии",
    "гранд сервис экспресс",
    "taxsee", "maxim — заказ такси", "maxim - заказ такси", "maximoff",
    "gismeteo", "гисметео",
    "ivi.client", "иви:",
    "more.play", "okko:",
    "zen.android", "дзен",
    "tnt_premier", "premier —", "premier -",
    "mtstv", "кион",
    "radioplayer", "радиоплеер",
    "medsi", "медси",
    "мать и дитя",
    "iomt.istok",
    "сателлит online",
    "м-лайн", "m-line",
    "inme",
    "yuwell anytime",
    "follow anytime", "anytime follow",
    "ican health", "ican reach",
    "mq cgm",
    "freestyle libre",
    "medtrum",
    "syai link",
    "poctech cgm",
    "hematonix",
    "дианянь",
    "lumipod", "glutec", "lumiflex",
    "trueconf", "труконф",
    "лизаалерт",
    "рувики",
    "добро.рф",
    "цезарь сателлит",
    "тензор",
    "скб контур",
    "эвотор",
    "мп. инспектор",
    "1с:",
    "hrlink",
    "кхл",
)

internal fun matchesQuickExclusionApp(name: String, packageName: String): Boolean {
    val packageLower = packageName.lowercase()
    if (packageLower in QuickExclusionExactPackages) return true
    val haystack = "$packageLower ${name.lowercase()}"
    return QuickExclusionKeywords.any(haystack::contains)
}
